name: MacOS build

on:
  workflow_dispatch:
  push:

jobs:
  macos:
    name: PHP ${{ matrix.php-version }} ${{ matrix.arch }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.1", "8.0"]
        arch: ["x86_64", "arm64"]
      max-parallel: 4
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download PHP Cli
        id: php_cli
        env:
          MICRO_CLI_RUN_ID: "2554976476"
          MICRO_CLI_ARTIFACT_HASH: "836852491eee2c2b98994ca7833ea748bb391fdbfd102f160d56e7d769ccf153"
        run: |
          gh run download ${{ env.MICRO_CLI_RUN_ID }} -R dixyes/lwmbs -n cli_${{ matrix.php-version }}_${{ matrix.arch }}_${{ MICRO_CLI_ARTIFACT_HASH }}
          chmod 755 ./php

      - name: Download Composer
        id: composer
        env:
          COMPOSER_VERSION: "2.3.7"
        run: |
          wget https://getcomposer.org/download/${{ COMPOSER_VERSION }}/composer.phar
          chmod 755 ./composer.phar

      - name: Vendor Installation
        id: vendor_installation
        run: |
          cd src
          ../php ../composer.phar install -o

      - name: Create ~/.box folder
        id: create_folder
        run: |    
          cd ~
          mkdir .box
          chmod 755 .box

      - name: Build Box
        id: box
        continue-on-error: true
        run: |
          echo ${GITHUB_WORKSPACE}
          ./php src/bin/hyperf.php config set github.access-token ${{ env.GITHUB_TOKEN }}
          ./php src/bin/hyperf.php config set-php-version ${{ matrix.php-version }}
          ./php src/bin/hyperf.php build-prepare
          ./php src/bin/hyperf.php build-self --no-dev
          mv ~/.box/box ./box

      - name: Upload artifact for box
        if: steps.box.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: box_php${{ matrix.php-version }}_${{ matrix.arch }}
          path: |
            box

      - name: Fail if box build failed
        if: steps.box.outcome != 'success'
        run: |
          false